CREATE TABLE quilts (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  quilt_name TEXT NOT NULL,
  width INTEGER,
  height INTEGER,
  border FLOAT,
  block_width INTEGER NOT NULL,
  block_height INTEGER NOT NULL,
  class_name TEXT NOT NULL,
  standard_pattern BOOLEAN NOT NULL,
  lookup_id TEXT
);